export const ProjectList = [
  {
    _id: 1,
    notify: "Full Stack",
    card_img: "./full-stack.png",
    badge1: "React",
    badge2: "Node",
    badge3: "MongoDB",
    badge4: "Express",
    name: "Ecommerce Website",
    link: "https://github.com/ruhulamin-et15/mernproject02.git",
  },
  {
    _id: 2,
    notify: "Front-end",
    card_img: "./front-end.jpg",
    badge1: "React",
    badge2: "Bootstrap",
    badge3: "HTML",
    badge4: "SCSS",
    name: "Admin Dashboard UI",
    link: "https://github.com/ruhulamin-et15/reactadminusing-sass.git",
  },
  {
    _id: 3,
    notify: "Back-end",
    card_img: "./back-end.png",
    badge1: "React",
    badge2: "Node",
    badge3: "MongoDB",
    badge4: "Express",
    name: "Booking APIs",
    link: "https://github.com/ruhulamin-et15/mernproject01.git",
  },
];
